version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mindmesh-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mindmesh}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-please_change_me}
      POSTGRES_DB: ${POSTGRES_DB:-mindmesh}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mindmesh"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mindmesh-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: