apiVersion: v1
kind: ConfigMap
metadata:
  name: mindmesh-config
  namespace: mindmesh
  labels:
    app: mindmesh
    version: v1
data:
  # Database Configuration
  POSTGRES_HOST: "postgresql-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mindmesh"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Application Configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # Service Discovery
  IDEAS_SERVICE_URL: "http://ideas-service:3001"
  VOTING_SERVICE_URL: "http://voting-service:3002"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3003"
  DECISION_SERVICE_URL: "http://decision-service:3004"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Monitoring
  METRICS_PORT: "9090"
  HEALTH_CHECK_PATH: "/health"
  
  # Security
  CORS_ORIGINS: "https://mindmesh.com,https://www.mindmesh.com"
  SESSION_TIMEOUT: "3600"
  
  # Performance
  MAX_CONCURRENT_REQUESTS: "100"
  REQUEST_TIMEOUT: "30000"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mindmesh
  labels:
    app: nginx
data:
  nginx.conf: |
    upstream backend {
        least_conn;
        server ideas-service:3001;
        server voting-service:3002;
        server analytics-service:3003;
        server decision-service:3004;
    }

    server {
        listen 80;
        server_name _;
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }